package Cookbook::Model::CookbookDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Cookbook::Schema',
    
    connect_info => {
        dsn => 'dbi:mysql:cookbook',
        user => 'root',
        password => 'solid',
    }
);

=head1 NAME

Cookbook::Model::CookbookDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Cookbook>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Cookbook::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.55

=head1 AUTHOR

Daniil Popov

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
